export const AFFIRMATIONS = [
  "I don’t chase, I attract. Everything that I want, simply finds me",
  "I deserve happiness and success",
  "I am truly comfortable in my body and I fully and whole heartedly love and accept myself",
  "I am super attractive to the people I am attracted to",
  "I have peace within me",
  "I look 25 always",
  "I always have the energy of a 25 year old",
  "I have the skin and body of A 25 year old",
  "I know I am worthy, I always see proof around me that I am worthy",
  "I am naturally happy and so self-assured",
  "I ooze joy and I am truly happy with my self",
  "My life is pure joy, every single day in every single way",
  "The whole universe is by my side",
  "Everything works out in my favor",
  "Everything that I want, is already mine",
  "Every day in every way my life gets better and better",
  "I am grateful for all the blessings of my life",
  "I am the best version of myself today",
  "Money comes to me in miraculous ways",
  "Money comes to me easily and effortlessly",
  "Every day my bank account is filled with more and more money",
  "My sources of income increase every month",
  "Money is effortlessly attracted to me",
  "My skin is glowing, smooth and youthful",
  "My skin is naturally clean and clear",
  "My hair is lush and voluminous and straight",
  "My hair is always black and straight smooth and naturally silky",
  "My health is in perfect condition and gets better every day",
  "My creativity finds an outlet in money-making ways every day",
  "I enjoy life and I play as life unfolds itself positively in front of my eyes",
  "I forgive myself",
  "I operate with the guidance of my higher self every day",
  "I fully accept and embrace my whole worth",
  "I put myself and my boundaries first",
  "Good things come to me easily, and naturally",
  "I am love",
  "I am perfection",
  "I am always chosen",
  "I am everyone’s top priority",
  "No one compares to me",
  "Nobody is better than me",
  "Today is the best day of my life yet",
  "I am life’s greatest gift that anybody can ever receive and they know it",
  "I always get exactly what I want-instantly, effortlessly, and without resistance.",
  "I’m a magnet for abundance, beauty, and blessings.",
  "The best of everything is drawn to me: the most luxurious experiences, the most incredible opportunities, the highest success, and the kind of wealth that makes life feel like a dream.",
  "Money flows to me in overflowing waves, success follows me wherever I go, and admiration surrounds me in a natural aura.",
  "I never have to try hard - everything I desire already knows its place is with me.",
  "I was born to have it all, and that’s exactly what I do every single day",
  "I attract wealth, recognition, and respect just by being myself.",
  "My life is a collection of yeses, of wins, and of “of course you did.”",
  "I get the soft life, the rich life, the dream life, and I receive it with calm confidence.",
  "People look at me and wonder how I always get what I want—but I know it’s just who I am.",
  "Reality bends for me, because I’m the main character, the one who always gets the most, the best, the finest. And every time I receive something amazing, the universe smiles and asks, “Is that all you wanted?”-because I know there's always more coming.",
  "I am always protected by the universe",
  "An Aura of divine protection and divine grace always envelops me",
  "Every move I make is always the best move making me millions",
  "God always shines through me and protects me 24*7",
  "I always only attract the best of people who have the best of intentions with me",
  "I get paid just to exist",
  "Money bends over backwards to make its way to my account",
  "I always have more than enough",
  "Every day every second my wealth increases",
  "I always know what to do, when to do it, and how to do it.",
  "I am surrounded by love, every day in all the good ways"
];
